import { createFileRoute } from "@tanstack/react-router";
import { ChevronDown } from "lucide-react";
import { useState } from "react";

export const Route = createFileRoute("/faq")({ head: () => ({ meta: [
  { title: "FAQ — MAISONNE" }, { name: "description", content: "Ответы на частые вопросы о доставке, гарантии и уходе за мебелью MAISONNE." },
  { property: "og:title", content: "FAQ — MAISONNE" }, { property: "og:description", content: "Всё важное о заказе мебели MAISONNE." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
]}), component: FaqPage });
const faq = [["Как оформить заказ?","Выберите модель и оставьте заявку на её странице. Консультант свяжется с вами, уточнит ткань, цвет и детали доставки."],["Сколько занимает производство?","Обычный срок изготовления и доставки — от 2 до 4 недель. Для отдельных тканей срок может отличаться."],["Можно ли заказать образцы тканей?","Да, мы бесплатно подберём и отправим образцы доступных тканей после консультации."],["Какая гарантия на мебель?","На каркас и механизмы действует гарантия 18 месяцев при соблюдении рекомендаций по эксплуатации."],["Можно ли вернуть товар?","Условия возврата зависят от того, была ли модель изготовлена индивидуально. Консультант расскажет детали до оформления."],["Как ухаживать за обивкой?","Используйте мягкую щётку или пылесос и избегайте агрессивных чистящих средств. Инструкция прилагается к заказу."]];
function FaqPage() { const [open,setOpen]=useState(0); return <div className="page-wrap min-h-[70vh] pb-28 pt-28 md:pt-36"><p className="text-xs uppercase tracking-[0.18em] text-olive">Поддержка</p><h1 className="mt-4 font-display text-6xl md:text-8xl">Вопросы и ответы</h1><div className="mt-16 max-w-4xl border-t border-border">{faq.map(([q,a],i)=><div key={q} className="border-b border-border"><button className="flex w-full items-center justify-between gap-8 py-7 text-left text-lg font-semibold" onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}>{q}<ChevronDown className={`shrink-0 transition ${open===i?"rotate-180 text-olive":""}`}/></button>{open===i&&<p className="max-w-2xl pb-7 text-sm leading-7 text-copy">{a}</p>}</div>)}</div></div> }